services:
  storage:
    image: alpine:latest
    volumes:
      - my_videos:/app:rw
    command: sh -c "mkdir -p /app/chrome /app/firefox /app/edge && chmod 777 /app/firefox /app/edge /app/chrome"

  chrome:
    image: selenium/node-chrome:4.32.0-20250515
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_NODE_MAX_SESSIONS=4

  edge:
    image: selenium/node-edge:4.32.0-20250515
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_NODE_MAX_SESSIONS=4

  firefox:
    image: selenium/node-firefox:4.32.0-20250515
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_NODE_MAX_SESSIONS=4

  chrome_video:
    image: selenium/video:ffmpeg-7.1-20250515
    volumes:
      - type: volume
        source: my_videos
        target: /videos
        volume:
          subpath: chrome
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto


  edge_video:
    image: selenium/video:ffmpeg-7.1-20250515
    volumes:
      - type: volume
        source: my_videos
        target: /videos
        volume:
          subpath: edge
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  firefox_video:
    image: selenium/video:ffmpeg-7.1-20250515
    volumes:
      - type: volume
        source: my_videos
        target: /videos
        volume:
          subpath: firefox
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  selenium-hub:
    image: selenium/hub:4.32.0-20250515
    container_name: selenium-hub
    depends_on:
      - storage
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  file_browser:
    image: filebrowser/filebrowser:latest
    container_name: file_browser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - my_videos:/srv
    environment:
      - FB_NOAUTH=true
      
volumes:
    my_videos: